"""initial schema: fleet, routes, trips, seats

Revision ID: 678d6fbc9ebe
Revises:
Create Date: 2026-09-14 01:23:43.540541

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "678d6fbc9ebe"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bus_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.Enum("mini", "standard", "large", name="bus_class"), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("column_count", sa.Integer(), nullable=False),
        sa.Column("seats_count", sa.Integer(), nullable=False),
        sa.Column(
            "layout",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("min_distance_km", sa.Integer(), nullable=False),
        sa.Column("max_distance_km", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "max_distance_km IS NULL OR max_distance_km >= min_distance_km",
            name=op.f("ck_bus_types_distance_range"),
        ),
        sa.CheckConstraint("seats_count > 0", name=op.f("ck_bus_types_seats_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bus_types")),
        sa.UniqueConstraint("code", name=op.f("uq_bus_types_code")),
    )
    op.create_table(
        "routes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("origin_city", sa.String(length=64), nullable=False),
        sa.Column("destination_city", sa.String(length=64), nullable=False),
        sa.Column("distance_km", sa.Integer(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("distance_km > 0", name=op.f("ck_routes_distance_positive")),
        sa.CheckConstraint("duration_minutes > 0", name=op.f("ck_routes_duration_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routes")),
        sa.UniqueConstraint("code", name=op.f("uq_routes_code")),
    )
    op.create_index("ix_routes_cities", "routes", ["origin_city", "destination_city"], unique=False)
    op.create_table(
        "buses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plate", sa.String(length=16), nullable=False),
        sa.Column("bus_type_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bus_type_id"],
            ["bus_types.id"],
            name=op.f("fk_buses_bus_type_id_bus_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buses")),
        sa.UniqueConstraint("plate", name=op.f("uq_buses_plate")),
    )
    op.create_index(op.f("ix_buses_bus_type_id"), "buses", ["bus_type_id"], unique=False)
    op.create_table(
        "trips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("bus_type_id", sa.Integer(), nullable=False),
        sa.Column("bus_id", sa.Integer(), nullable=True),
        sa.Column("departure_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("arrival_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("scheduled", "delayed", "departed", "cancelled", name="trip_status"),
            nullable=False,
        ),
        sa.Column("base_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bus_id"], ["buses.id"], name=op.f("fk_trips_bus_id_buses"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["bus_type_id"],
            ["bus_types.id"],
            name=op.f("fk_trips_bus_type_id_bus_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["route_id"], ["routes.id"], name=op.f("fk_trips_route_id_routes"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trips")),
        sa.UniqueConstraint("route_id", "departure_at", name="uq_trips_route_departure"),
    )
    op.create_index("ix_trips_departure_at", "trips", ["departure_at"], unique=False)
    op.create_index("ix_trips_route_departure", "trips", ["route_id", "departure_at"], unique=False)
    op.create_table(
        "seats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=8), nullable=False),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column("column_index", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("free", "held", "sold", name="seat_status"), nullable=False),
        sa.Column("held_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_seats_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seats")),
        sa.UniqueConstraint("trip_id", "number", name="uq_seats_trip_number"),
    )
    op.create_index("ix_seats_trip_status", "seats", ["trip_id", "status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_seats_trip_status", table_name="seats")
    op.drop_table("seats")
    op.drop_index("ix_trips_route_departure", table_name="trips")
    op.drop_index("ix_trips_departure_at", table_name="trips")
    op.drop_table("trips")
    op.drop_index(op.f("ix_buses_bus_type_id"), table_name="buses")
    op.drop_table("buses")
    op.drop_index("ix_routes_cities", table_name="routes")
    op.drop_table("routes")
    op.drop_table("bus_types")
    # ### end Alembic commands ###
